export const getUsers = async (request, response) => {

    try{

    }catch(error){
        console.log(error)
        response.status(500).json({ message: "Failed to get users" })
    }

}

export const getUser = async (request, response) => {

    try{

    }catch(error){
        console.log(error)
        response.status(500).json({ message: "Failed to get user" })
    }

}

export const updateUser = async (request, response) => {

    try{

    }catch(error){
        console.log(error)
        response.status(500).json({ message: "Failed to update user" })
    }

}

export const deleteUser = async (request, response) => {

    try{

    }catch(error){
        console.log(error)
        response.status(500).json({ message: "Failed to delete user" })
    }

}